name: task_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  get_it: ^8.0.2
  injectable: ^2.5.0
  injectable_generator: ^2.6.2
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  json_annotation: ^4.9.0
  json_serializable: ^6.9.0
  flutter_bloc: ^8.1.6
  retrofit: ^4.4.1
  go_router: ^7.0.0
  freezed_annotation: ^2.4.4
  crypto: ^3.0.6
  fpdart: ^1.1.1
  async: ^2.11.0
  fluttertoast: ^8.2.8
  flutter_secure_storage: ^9.2.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^9.1.5
  build_runner: ^2.4.13
  analyzer: ^6.5.0
  freezed: ^2.5.7  
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
